site_name: AiDraw
site_description: 一个介绍 Ai 绘画的 WIKI/A WIKI about Ai painting
site_url: 'https://stable-diffusion-book.vercel.app/'
site_author: StableDiffusionBook Team
repo_url: 'https://github.com/sudoskys/StableDiffusionBook'
edit_uri: edit/main/docs/
copyright: |
  Copyright &copy; 采用 GFDL 协议

nav:
  - 起步于此:
      - index.md
      - 新闻: GettingStarted/news.md
      - 术语: GettingStarted/term.md
      - 声明: GettingStarted/state.md
      - 贡献指南: GettingStarted/contributing.md
      
  - 开始之前:
      - Perpare/index.md
  - 安装配置:
      - install/index.md
      - WebUi安装:
          - install/WebUi/index.md
          - 运行WebUi: install/WebUi/launch.md
          - 错误处理: install/WebUi/Troubleshoot.md
  - 绘画调试:
      - model/index.md
      - GPU相关: model/GPU.md
      - NAI泄漏报告: model/NAI.md
      - WebUi 配置:
          - model/WebUi/index.md
          - 基本指南: model/WebUi/base.md
          - 错误处理: model/WebUi/Troubleshoot.md
  - 绘画指南:
      - paint/index.md
      - WebUi绘画指南:
          - paint/WebUi/index.md
          - 基本指南: paint/WebUi/base.md
          
          - 进阶指南: paint/WebUi/Advanced.md
          - 安装扩展: paint/WebUi/extension.md
      - 实战指南: 
          - paint/Practicalguide.md
  - 训练模型:
      - 训练介绍: train/index.md
      - Textual 训练: train/Textual.md
      - Hypernetwork 训练: train/Hypernetwork.md
      - DreamBooth 训练: train/DreamBooth.md
      - AestheticGradients 训练: train/AestheticGradients.md
  - 参考资料:
      - landing/index.md

theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - toc.follow
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.expand
    - navigation.sections

markdown_extensions:
  - tables
  - attr_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: 'https://t.me/s/StableDiffusion_CN_WIKI'
    - icon: fontawesome/brands/telegram
      link: 'https://t.me/s/StableDiffusion_Show'
  generator: true

plugins:
  - search
  - i18n:
      material_alternate: true
      default_language: zh
      nav_translations:
        en:
            起步于此: Start here
            术语: Terminology
            新闻: News
            声明: Statement
            开始之前: Before start
            安装配置: Installation
            WebUi安装: Install SDWebUi
            绘画调试: Configuration
            GPU相关: Gpu Debuging
            NAI泄漏报告: NAI leak report
            WebUi配置模型: Configrue Model for WebUi
            绘画指南: Paint guide
            基本指南: Base guide
            WebUi绘画指南: Paint With WebUi
            实战指南: Application Guide
            进阶指南: Advanced Guide
            安装扩展: Extension
            训练模型: Train Model
            训练介绍: Intro
            Textual 训练: Textual Inversion
            Hypernetwork 训练:  Hypernetwork
            DreamBooth 训练: DreamBooth
            AestheticGradients 训练: AestheticGradients
            参考资料: References
            运行WebUi: LaunchWebUi
            错误处理: Troubleshoot
            工作台: Workstations
            贡献指南: Contribution Guide
      languages:
        en:
          name: English
        zh:
          name: 简体中文
  - git-revision-date-localized:
      type: datetime
      enable_creation_date: true

# 起步于此:
# 术语:
# 新闻:
# 声明:
# 开始之前:
# 安装配置:
# WebUi安装:
# 装置调试:
# GPU相关:
# NAI泄漏报告:
# WebUi配置模型:
# 绘画调试:
# WebUi绘画指南:
# 应用指南:
# 进阶指南:
# 参数:
# 训练模型:
# 训练介绍:
# Textual 训练:
# Hypernetwork 训练:
# DreamBooth 训练:
# AestheticGradients 训练:
# 参考资料:
