site_name: AiDraw
site_url: https://stable-diffusion-book.vercel.app/
nav:
    - 首页: index.md
    - 安装运行: set.md
    - 模型技法: fix.md
    - 调参魔法: mofa.md
    - 社区支持: about.md
theme:
  name: material
  language: zh
  palette:
    primary: teal
    accent: teal
  features:
    - navigation.tabs
    - toc.integrate
    - toc.follow
    #- navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.expand
    

    
markdown_extensions:
  - tables
  - attr_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/s/StableDiffusion_CN_WIKI
    - icon: fontawesome/brands/telegram
      link: https://t.me/s/StableDiffusion_Show
      
plugins:
  # - git-authors
  - git-revision-date-localized:
      type: datetime
      enable_creation_date: true
  - search


repo_url: https://github.com/sudoskys/StableDiffusionBook
edit_uri: edit/main/docs/

copyright: >
        Copyright &copy; 非盈利开源文档
