site_name: AiDraw
site_url: https://stable-diffusion-book.vercel.app/
nav:
    - 术语解释: index.md
    - 起步于此: 2_prepare.md
    - 安装配置: 3_install.md
    - 模型调试: 4_model.md
    - 绘画调试: 5_drawing.md
    - 训练模型: 6_selftrain.md
    - 参考资料: 7_landing.md

theme:
  name: material
  language: zh
  palette:
    primary: teal
    accent: teal
  features:
    - navigation.tabs
    - toc.integrate
    - toc.follow
    # - navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.expand
    

    
markdown_extensions:
  - tables
  - attr_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/s/StableDiffusion_CN_WIKI

    - icon: fontawesome/brands/telegram
      link: https://t.me/s/StableDiffusion_Show
      
plugins:
  # - git-authors
  - git-revision-date-localized:
      type: datetime
      enable_creation_date: true
  - search


repo_url: https://github.com/sudoskys/StableDiffusionBook
edit_uri: edit/main/docs/

copyright: >
        Copyright &copy; BY-SA-NC 4.0,由爱好者共同构建
